[workspace]
authors = ["Fredrick Eisele <fred.eisele@vanderbilt.edu>"]
channels = ["http://localhost:19000/pixi-local/meso-forge", "https://prefix.dev/meso-forge", "conda-forge"]
name = "talos-dains-argocd"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
