apiVersion: v1
kind: Service
metadata:
  labels:
    app: pricelist-app
    tier: frontend
  name: pricelist-svc
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "4"
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: pricelist-app
    tier: frontend
status:
  loadBalancer: {}
