kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    oldname: pricelist-db-pvc
    oldfile: pricelist-db-pvc.yaml
    newfile: pricelist-db-pvc.yaml
  name: pricelist-db-pvc
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "1"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
