apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pricelist-db
    tier: database
  name: pricelist-db-deploy
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pricelist-db
      tier: database
  strategy: {}
  template:
    metadata:
      labels:
        app: pricelist-db
        tier: database
    spec:
      containers:
        - image: mysql:5.6.51
          name: pricelist-db
          env:
            - name: MYSQL_DATABASE
              value: pricelist
            - name: MYSQL_PASSWORD
              value: pricelist
            - name: MYSQL_USER
              value: pricelist
            - name: MYSQL_RANDOM_ROOT_PASSWORD
              value: "yes"
          volumeMounts:
            - mountPath: /var/lib/mysql/data
              name: mysql-db
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 12
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 12
            periodSeconds: 10
      volumes:
        - name: mysql-db
          persistentVolumeClaim:
            claimName: pricelist-db-pvc
